# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668559aa32667722a74bf458de5794c240e88e1c43b42b8fe158a46649d8a39e05244ecb7fd54d7dc1476478c83315e03629a02130be1df0e707b0de7e203747

test:
  secret_key_base: 9b22f26549e92fefbdefe52efaad597ad74a681dc5725ddc9c9876543b2ce043918154d0fed68fec5874d54533d6841a07a43cadb8714aecc00ffa4e238803fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
